add debug logs

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -70,10 +70,10 @@ jobs:
       #       ${{ runner.os }}-nuxt-build-
       - name: Install dependencies
         run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
-      - name: Show Node.js version
-        run: node -v
-      - name: Show npm version
-        run: npm -v
+      - name: Show directory contents
+        run: ls -la
+      - name: Show nuxt.config.ts contents
+        run: cat nuxt.config.ts || echo "Config not found"
       - name: Show nuxi info
         run: npx nuxi info
       - name: Static HTML export with Nuxt
